server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:7000
    password: "123456"
    read_timeout: 0.2s
    write_timeout: 0.2s
